### PR TITLE
Update runtastic.py

### PR DESCRIPTION
**Pull request by KitKat-MyBreak**
Windows only: can use ":" in file name.
Replace ":" by "-"

### CODE REVIEW

**Comment by yihong0618** [comment]
> Windows only: can use ":" in file name.
> 
> Replace ":" by "-"

@KitKat-MyBreak Thank you，I will test on my win10 later. Can we only change the gpx file name on windows?

**Comment by KitKat-MyBreak** [comment]
> 
> 
> > Windows only: can use ":" in file name.
> > Replace ":" by "-"
> 
> @KitKat-MyBreak Thank you，I will test on my win10 later. Can we only change the gpx file name on windows?

Yep you can, just don't use ":". Your script works perfectly after that.

**Comment by yihong0618** [comment]
@KitKat-MyBreak  Thank you very much
Merged

**Comment by yihong0618** [comment]
@KitKat-MyBreak I changed file name to unix timestamp

**Pull request merged**
